import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#9f3c00",
        "primary-container": "#c74e00",
        "primary-fixed": "#ffdbcd",
        "primary-fixed-dim": "#ffb596",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "secondary": "#7d5800",
        "secondary-container": "#fdbb33",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6d4c00",
        "tertiary": "#8c4b00",
        "tertiary-container": "#b06000",
        "on-tertiary": "#ffffff",
        "background": "#fcf9f7",
        "on-background": "#1b1c1b",
        "surface": "#fcf9f7",
        "surface-card": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f1",
        "surface-container": "#f0edeb",
        "surface-container-high": "#eae8e6",
        "surface-container-highest": "#e5e2e0",
        "surface-variant": "#e5e2e0",
        "surface-accent": "#F5EFEA",
        "on-surface": "#1b1c1b",
        "on-surface-variant": "#594138",
        "text-primary": "#1A110E",
        "text-secondary": "#594138",
        "border-subtle": "#EBE2DE",
        "outline": "#8d7166",
        "outline-variant": "#e1bfb2",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.375rem",
        sm: "0.25rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "max-width": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        headline: ["var(--font-manrope)", "sans-serif"],
        display: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
